# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: TicStatToe
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
