name: Java CI/CD with Maven and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}  # Set DB_PASSWORD globally for the build job

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: TicStatToe
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Log PostgreSQL Password
        run: echo "DB_PASSWORD is $DB_PASSWORD"

      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test with Maven
        run: mvn -B clean verify --file pom.xml

  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build  # Replace with your build command if different

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Deploy the 'build' directory to the 'gh-pages' branch
          git checkout --orphan gh-pages
          git rm -rf .
          mv build/* .
          echo "Your GitHub Pages URL: https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/" > README.md
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force

